name: Build and Release

on:
  push:
    branches:
    - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: '1.23'

    - name: Install dependencies
      run: go mod tidy

    - name: Install frontend dependencies
      run: npm install
      working-directory: frontend

    - name: Build frontend
      run: npm run build
      working-directory: frontend

    - name: Build binaries for Linux
      run: |
        mkdir -p build/linux
        GOOS=linux GOARCH=amd64 go build -o build/linux/Slender

    - name: Build binaries for Windows
      run: |
        mkdir -p build/windows
        GOOS=windows GOARCH=amd64 go build -o build/windows/Slender.exe

    - name: Get latest tag
      id: get_latest_tag
      run: |
        latest_tag=$(git tag --list 'v*' | sort -V | tail -n 1)
        echo "LATEST_TAG=$latest_tag" >> $GITHUB_ENV

    - name: Increment tag
      id: increment_tag
      run: |
        latest_tag="${{ env.LATEST_TAG }}"
        if [ -z "$latest_tag" ]; then
          new_tag="v0.0.1"
        else
          # Extract version numbers
          IFS='.' read -r major minor patch <<< "${latest_tag#v}"
          # Increment the patch number
          new_patch=$((patch + 1))
          new_tag="v${major}.${minor}.${new_patch}"
        fi
        echo "NEW_TAG=$new_tag" >> $GITHUB_ENV

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      with:
        tag_name: ${{ env.NEW_TAG }}
        release_name: Release ${{ env.NEW_TAG }}
        body: |
          Automatically generated release for tag ${{ env.NEW_TAG }}.
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Upload Linux Release Asset
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: build/linux/Slender
        asset_name: Slender-linux-amd64
        asset_content_type: application/octet-stream

    - name: Upload Windows Release Asset
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: build/windows/Slender.exe
        asset_name: Slender-windows-amd64.exe
        asset_content_type: application/octet-stream
